-- ============================================================
-- 20260805-add-statement-import.sql
-- Importación masiva de transacciones desde extractos bancarios
-- (PDF, incluye PDF con contraseña). Proceso asíncrono:
--   * finance.statement_import   -> lote de carga (estado y totales)
--   * finance.statement_import_file -> archivo individual (éxito/error)
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'statement_import_status_enum') THEN
    CREATE TYPE statement_import_status_enum AS ENUM (
      'pending', 'processing', 'completed', 'partial', 'failed'
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS finance.statement_import (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  status statement_import_status_enum NOT NULL DEFAULT 'pending',
  total_files INT NOT NULL DEFAULT 0,
  processed_files INT NOT NULL DEFAULT 0,
  success_files INT NOT NULL DEFAULT 0,
  failed_files INT NOT NULL DEFAULT 0,
  total_records_parsed INT NOT NULL DEFAULT 0,
  total_records_created INT NOT NULL DEFAULT 0,
  total_records_skipped INT NOT NULL DEFAULT 0,
  total_records_failed INT NOT NULL DEFAULT 0,
  options JSONB NOT NULL DEFAULT '{}'::jsonb,
  error JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_statement_import_user
  ON finance.statement_import (user_id, created_at DESC);

COMMENT ON COLUMN finance.statement_import.options
  IS 'Opciones de la carga (default_category_id, account_id, skip_duplicates, default_type). NUNCA almacenar contraseñas de PDF.';

CREATE TABLE IF NOT EXISTS finance.statement_import_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id BIGINT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  mimetype VARCHAR(100) NOT NULL DEFAULT '',
  size_bytes BIGINT NOT NULL DEFAULT 0,
  storage_path TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  records_parsed INT NOT NULL DEFAULT 0,
  records_created INT NOT NULL DEFAULT 0,
  records_skipped INT NOT NULL DEFAULT 0,
  error_code VARCHAR(60),
  error_message TEXT,
  processed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_statement_import_file_import
    FOREIGN KEY (import_id) REFERENCES finance.statement_import(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_statement_import_file_import
  ON finance.statement_import_file (import_id);

COMMENT ON COLUMN finance.statement_import_file.storage_path
  IS 'Ruta temporal del archivo en disco mientras se procesa el lote. Se elimina al terminar.';
