-- ============================================================
-- 20260806-add-category-status-installments-otp.sql
-- Mejoras de categorización, cuotas, recuperación por OTP y
-- plantillas de correo react.email.
--   * finance.transaction_record
--       - category_id pasa a nullable (importaciones sin categoría)
--       - category_status   -> 'categorized' | 'pending' (por editar)
--       - installments      -> nº de cuotas de la compra
--       - installment_value -> valor de cada cuota
--   * finance.transaction_category_rule  -> auto-categorización por
--     descripción normalizada (description -> categoría)
--   * identity.password_reset_otp        -> códigos OTP para
--     recuperación de contraseña
--   * mail.email_template                -> plantillas react.email
--     personalizables (key, subject, html_body)
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'review_status_enum') THEN
    CREATE TYPE review_status_enum AS ENUM ('categorized', 'pending');
  END IF;
END
$$;

-- ── finance.transaction_record ──────────────────────────────
ALTER TABLE finance.transaction_record
  ALTER COLUMN category_id DROP NOT NULL;

ALTER TABLE finance.transaction_record
  ADD COLUMN IF NOT EXISTS category_status review_status_enum NOT NULL DEFAULT 'categorized';

ALTER TABLE finance.transaction_record
  ADD COLUMN IF NOT EXISTS installments SMALLINT;

ALTER TABLE finance.transaction_record
  ADD COLUMN IF NOT EXISTS installment_value NUMERIC(15,2);

ALTER TABLE finance.statement_import
  ADD COLUMN IF NOT EXISTS total_records_uncategorized INT NOT NULL DEFAULT 0;

ALTER TABLE finance.statement_import_file
  ADD COLUMN IF NOT EXISTS records_uncategorized INT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_transaction_category_status
  ON finance.transaction_record (user_id, category_status);

CREATE INDEX IF NOT EXISTS idx_transaction_description
  ON finance.transaction_record (user_id, lower(description));

COMMENT ON COLUMN finance.transaction_record.category_status
  IS 'Estado de revisión de la categoría: categorized (definida) | pending (por editar).';
COMMENT ON COLUMN finance.transaction_record.installments
  IS 'Número de cuotas de la compra cuando aplica (tarjeta crédito).';
COMMENT ON COLUMN finance.transaction_record.installment_value
  IS 'Valor de cada cuota cuando la compra tiene financiación.';

-- ── finance.transaction_category_rule ───────────────────────
CREATE TABLE IF NOT EXISTS finance.transaction_category_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  normalized_description TEXT NOT NULL,
  category_id BIGINT NOT NULL,
  subcategory_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT uq_transaction_category_rule
    UNIQUE (user_id, normalized_description),
  CONSTRAINT fk_transaction_category_rule_category
    FOREIGN KEY (category_id) REFERENCES catalog.category (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transaction_category_rule_user
  ON finance.transaction_category_rule (user_id, normalized_description);

COMMENT ON TABLE finance.transaction_category_rule
  IS 'Reglas de auto-categorización: descripción normalizada de la transacción -> categoría asignada por el usuario.';

-- ── identity.password_reset_otp ─────────────────────────────
CREATE TABLE IF NOT EXISTS identity.password_reset_otp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP,
  attempts INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_otp_user
    FOREIGN KEY (user_id) REFERENCES identity.app_user (id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_otp_user
  ON identity.password_reset_otp (user_id, created_at DESC);

COMMENT ON TABLE identity.password_reset_otp
  IS 'Códigos OTP de recuperación de contraseña. Se almacena hash SHA-256, nunca el código en claro.';

-- ── mail.email_template ─────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS mail;

CREATE TABLE IF NOT EXISTS mail.email_template (
  key VARCHAR(60) PRIMARY KEY,
  subject VARCHAR(255) NOT NULL,
  html_body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT chk_email_template_subject
    CHECK (char_length(subject) BETWEEN 1 AND 255)
);

COMMENT ON TABLE mail.email_template
  IS 'Plantillas de correo personalizables desde el editor react.email (Inspector). key identifica el tipo de email.';
